spring.application.name=MicroLearnConfigServer
server.port=8012

spring.cloud.config.server.git.uri=${CONFIG_SERVER_GIT_URI:https://github.com/rishavm22/MicroServiceProject-MicroConfigServer}
spring.cloud.config.server.git.username=${CONFIG_SERVER_GIT_USERNAME:}
spring.cloud.config.server.git.password=${CONFIG_SERVER_GIT_PASSWORD:}
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main
